---
# Development compose file

# docker-compose version
version: '3.7'

services: 
  server:
    # specify location and build target of docker file
    build:
      # directory of dockerfile
      context: ./server
      target: build

    ports:
      # local machine : container
      - "8080:8080"

    volumes:
      - ./server:/app
      - server_modules:/app/node_modules

    networks:
      - database
      - frontend

    depends_on:
      - database

  database:
    tty: true
    image: postgres:13.1
    networks:
      - database
    environment:
      USER_PASSWORD: "pw123"
      POSTGRES_PASSWORD: "pw123"

    volumes:
      - data:/var/lib/postgresql/data 
      - ./baltimore-homicide-victims.csv:/docker-entrypoint-initdb.d/csv/data.csv
      - ./init.sql:/docker-entrypoint-initdb.d/sql/init.sql

networks:
  database:
  frontend:

# storage
volumes:
  data:
  server_modules: